// scraper.js — Run once with: node scraper.js
// Fetches full-year 2025 HILO tide predictions for representative NOAA stations
// in each Pacific coast region, computes percentile-based quality thresholds,
// and writes tideConstants.js for use by tidetracker.html.

const https = require('https');
const fs    = require('fs');
const path  = require('path');

const NOAA_BASE = 'https://api.tidesandcurrents.noaa.gov/api/prod/datagetter';

// One representative station per region
const STATIONS = [
  { id: '9451600', region: 'alaska',     name: 'Sitka, AK' },
  { id: '9443090', region: 'pnw',        name: 'Neah Bay, WA (PNW/BC proxy)' },
  { id: '9444900', region: 'washington', name: 'Port Townsend, WA' },
  { id: '9435380', region: 'oregon',     name: 'South Beach, OR' },
  { id: '9414290', region: 'norcal',     name: 'San Francisco, CA' },
  { id: '9410660', region: 'socal',      name: 'Los Angeles, CA' },
];

// Geographic bounding boxes for region matching (checked in order)
const REGION_BOUNDS = {
  alaska:     { latMin: 54,  latMax: 90,  lonMin: -180, lonMax: -100 },
  pnw:        { latMin: 48,  latMax: 54,  lonMin: -140, lonMax: -120 },
  washington: { latMin: 45,  latMax: 49,  lonMin: -125, lonMax: -116 },
  oregon:     { latMin: 42,  latMax: 45,  lonMin: -125, lonMax: -116 },
  norcal:     { latMin: 36,  latMax: 42,  lonMin: -125, lonMax: -116 },
  socal:      { latMin: 22,  latMax: 36,  lonMin: -120, lonMax: -106 },
};

const REGION_NAMES = {
  alaska:     'Alaska',
  pnw:        'Pacific Northwest / BC',
  washington: 'Washington',
  oregon:     'Oregon',
  norcal:     'Northern California',
  socal:      'Southern California / Baja',
};

function fetchUrl(url) {
  return new Promise((resolve, reject) => {
    https.get(url, res => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        try { resolve(JSON.parse(body)); }
        catch (e) { reject(new Error('JSON parse error: ' + e.message)); }
      });
    }).on('error', reject);
  });
}

async function fetchHiLoYear(stationId) {
  // NOAA allows max 1 year per request for hilo
  const url = `${NOAA_BASE}?product=predictions&datum=MLLW&time_zone=lst_ldt` +
    `&interval=hilo&units=english&application=nudibranchnerd&format=json` +
    `&station=${stationId}&begin_date=20250101&end_date=20251231`;
  console.log(`  Fetching ${stationId}…`);
  const data = await fetchUrl(url);
  if (data.error) throw new Error(`NOAA error for ${stationId}: ${data.error.message}`);
  return data.predictions || [];
}

function computeThresholds(predictions) {
  // Filter to low tides only
  const lows = predictions
    .filter(p => p.type === 'L')
    .map(p => parseFloat(p.v))
    .filter(v => !isNaN(v))
    .sort((a, b) => a - b);

  const n = lows.length;
  if (n < 10) throw new Error(`Not enough low tide data (${n} lows)`);

  // Percentile indices (0-based)
  // Exceptional: ~4 per year  → 4/n of sorted lows
  // Great:       ~12 per year → 12/n
  // Good:        ~66 per year → 66/n  (≈5-6/month)
  const exceptionalIdx = Math.min(Math.ceil(4)  - 1, n - 1);
  const greatIdx       = Math.min(Math.ceil(12) - 1, n - 1);
  const goodIdx        = Math.min(Math.ceil(Math.round(n * 0.09)) - 1, n - 1);

  return {
    exceptional: parseFloat(lows[exceptionalIdx].toFixed(2)),
    great:       parseFloat(lows[greatIdx].toFixed(2)),
    good:        parseFloat(lows[goodIdx].toFixed(2)),
    _count:      n,
  };
}

async function main() {
  console.log('Nudibranch Nerd — Tide Threshold Scraper');
  console.log('Fetching 2025 HILO data from NOAA CO-OPS…\n');

  const results = {};

  for (const station of STATIONS) {
    try {
      const preds = await fetchHiLoYear(station.id);
      const t = computeThresholds(preds);
      results[station.region] = t;
      console.log(`  ✓ ${REGION_NAMES[station.region]} (${station.name})`);
      console.log(`    ${t._count} low tides | exceptional ≤ ${t.exceptional} ft | great ≤ ${t.great} ft | good ≤ ${t.good} ft\n`);
      // Polite delay between requests
      await new Promise(r => setTimeout(r, 800));
    } catch (err) {
      console.error(`  ✗ ${station.region}: ${err.message}`);
      process.exitCode = 1;
    }
  }

  // Build tideConstants.js content
  const regions = Object.entries(REGION_BOUNDS).map(([id, bounds]) => {
    const t = results[id];
    if (!t) {
      console.warn(`  Warning: no thresholds for region "${id}", skipping`);
      return null;
    }
    return {
      id,
      name: REGION_NAMES[id],
      ...bounds,
      thresholds: { exceptional: t.exceptional, great: t.great, good: t.good },
    };
  }).filter(Boolean);

  const js = `// tideConstants.js — Auto-generated by scraper.js on ${new Date().toISOString().slice(0,10)}
// Do not edit manually — re-run: node scraper.js
//
// Thresholds derived from full-year 2025 NOAA HILO data for representative stations.
// exceptional ≈ 4 lowest lows of the year
// great       ≈ 12 lowest lows (monthly highlight)
// good        ≈ 9th percentile (5-6 per month)

const TIDE_REGIONS = ${JSON.stringify(regions, null, 2)};

// Fallback for locations outside defined regions (East Coast, Gulf, Hawaii, etc.)
const TIDE_THRESHOLDS_DEFAULT = { exceptional: -0.5, great: 0.0, good: 0.5 };
`;

  const outPath = path.join(__dirname, 'tideConstants.js');
  fs.writeFileSync(outPath, js, 'utf8');
  console.log(`\nWrote ${outPath}`);
  console.log('Done! Load tideConstants.js in tidetracker.html.');
}

main().catch(err => {
  console.error('Fatal:', err.message);
  process.exit(1);
});
