// tideConstants.js — Auto-generated by scraper.js on 2026-03-17
// Do not edit manually — re-run: node scraper.js
//
// Thresholds derived from full-year 2025 NOAA HILO data for representative stations.
// exceptional ≈ 4 lowest lows of the year
// great       ≈ 12 lowest lows (monthly highlight)
// good        ≈ 9th percentile (5-6 per month)

const TIDE_REGIONS = [
  {
    "id": "alaska",
    "name": "Alaska",
    "latMin": 54,
    "latMax": 90,
    "lonMin": -180,
    "lonMax": -100,
    "thresholds": {
      "exceptional": -2.85,
      "great": -2.59,
      "good": -1.35
    }
  },
  {
    "id": "pnw",
    "name": "Pacific Northwest / BC",
    "latMin": 48,
    "latMax": 54,
    "lonMin": -140,
    "lonMax": -120,
    "thresholds": {
      "exceptional": -2.5,
      "great": -2.0,
      "good": -1
    }
  },
  {
    "id": "washington",
    "name": "Washington",
    "latMin": 45,
    "latMax": 49,
    "lonMin": -125,
    "lonMax": -116,
    "thresholds": {
      "exceptional": -3.64,
      "great": -3.14,
      "good": -1.67
    }
  },
  {
    "id": "oregon",
    "name": "Oregon",
    "latMin": 42,
    "latMax": 45,
    "lonMin": -125,
    "lonMax": -116,
    "thresholds": {
      "exceptional": -2.43,
      "great": -2.17,
      "good": -1.07
    }
  },
  {
    "id": "norcal",
    "name": "Northern California",
    "latMin": 36,
    "latMax": 42,
    "lonMin": -125,
    "lonMax": -116,
    "thresholds": {
      "exceptional": -1.69,
      "great": -1,
      "good": 0
    }
  },
  {
    "id": "socal",
    "name": "Southern California / Baja",
    "latMin": 22,
    "latMax": 36,
    "lonMin": -120,
    "lonMax": -106,
    "thresholds": {
      "exceptional": -1.71,
      "great": -1.51,
      "good": 0
    }
  }
];

// Fallback for locations outside defined regions (East Coast, Gulf, Hawaii, etc.)
const TIDE_THRESHOLDS_DEFAULT = { exceptional: -0.5, great: 0.0, good: 0.5 };
